### ISSUE TITLE
 ktunnel inject fails

### ISSUE THREAD

**Issue by artemsalimov** [omrikiei/ktunnel#115]
ktunnel inject deployment singlespace-deployment  -n sa-dev 8080                                   
INFO[0000] Injecting tunnel sidecar to sa-dev/singlespace-deployment 
WARN[0001] docker.io/omrieival/ktunnel:v1.5.3 already injected to the deplyoment 
INFO[0001] ProgressDeadlineInSeconds is currently 600s. It may take this long to detect a deployment failure. 
INFO[0001] Waiting for deployment to be ready           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2023b53]

goroutine 9 [running]:
github.com/omrikiei/ktunnel/pkg/k8s.deploymentStatus(0xc00019cf00)
        /home/runner/work/ktunnel/ktunnel/pkg/k8s/common.go:404 +0x693
github.com/omrikiei/ktunnel/pkg/k8s.watchForReady.func1()
        /home/runner/work/ktunnel/ktunnel/pkg/k8s/common.go:377 +0x385
created by github.com/omrikiei/ktunnel/pkg/k8s.watchForReady
        /home/runner/work/ktunnel/ktunnel/pkg/k8s/common.go:331 +0x72

What is wrong

**Comment by omrikiei** [comment]
looks like there's an ungraceful error handling, was there already an injected sidecar of ktunnel to this deployment? is expose a viable alternative?

**Comment by omrikiei** [comment]
Both halves of this are fixed as of v2.2.0.

**The panic.** `deploymentStatus` dereferenced `spec.replicas` and the progressing condition without checking either for nil. Both are guarded now, and a read that fails while waiting for a rollout is reported as an error rather than taken down the process.

**The reason `inject` was not working in the first place.** Even without the panic it could never have forwarded to your deployment. Pods were resolved with a hardcoded selector — `app.kubernetes.io/name=<name>,app.kubernetes.io/instance=<name>` — which are labels `expose` puts on the deployments it creates itself. `inject` patches a deployment you own and does not add them, so nothing ever matched: the sidecar went in, the pod reported Running, and the forward retried forever. Pods are now resolved through the deployment's own `spec.selector`. That was #171, and it means `inject` had been broken for everyone, for years, not just for you.

While there: `inject` no longer refuses deployments with more than one replica (#96), and a pod that is terminating is no longer picked as the forward target.

Worth upgrading to v2.2.0 — you were on v1.5.3.
